[package]
name = "codecrafters-redis"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytes = "1.10.1"
dashmap = "6.1.0"
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["full"] }
